name: check-upstream
on:
  push:
    branches: main
  schedule:
  # run on every day
    - cron: '0 0 * * *'
jobs:
  update:
    name: update url and version to the lastest commit
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip
      - name: update version
        run: |-
          pip install -r requirements
          ./update_version.py
          git config --global user.email "33030965+tizee@users.noreply.github.com"
          git config --global user.name "tizee"
          git add --all
          git commit -m "bot update verion" || exit 0
          git push
